//
//  PokemonListModels.swift
//  PokemonVIP
//
//  Created by Ihwan on 05/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PokemonList
{
    enum FetchPokemons
    {
        struct Request
        {
        }
        struct Response
        {
            var pokemons: [Pokemon]
        }
        struct ViewModel
        {
            
            struct DisplayedPokemon
            {
                var name: String
            }
            var displayedPokemons: [DisplayedPokemon]
        }
    }
}

struct Pokemon: Decodable{
    var name: String
}

struct BaseResponse: Decodable{
    var data: [Pokemon]
}
