//
//  PokemonListRouter.swift
//  PokemonVIP
//
//  Created by Ihwan on 05/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PokemonListRoutingLogic
{
    func routeToPokemonDetail(segue: UIStoryboardSegue?)
}

protocol PokemonListDataPassing
{
    var dataStore: PokemonListDataStore? { get }
}

class PokemonListRouter: NSObject, PokemonListRoutingLogic, PokemonListDataPassing
{
    weak var viewController: PokemonListViewController?
    var dataStore: PokemonListDataStore?
    
    // MARK: Routing
    
    func routeToPokemonDetail(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! PokemonDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
       passDataToPokemonDetail(source: dataStore!, destination: &destinationDS)
      } else {
          let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "PokemonDetailViewController") as! PokemonDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
          passDataToPokemonDetail(source: dataStore!, destination: &destinationDS)
        navigateToPokemonDetail(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToPokemonDetail(source: PokemonListViewController, destination: PokemonDetailViewController)
    {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToPokemonDetail(source: PokemonListDataStore, destination: inout PokemonDetailDataStore)
    {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.pokemon = source.pokemons?[selectedRow!]
        
    }
}
