//
//  PokemonListInteractor.swift
//  PokemonVIP
//
//  Created by Ihwan on 05/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonListBusinessLogic
{
    func fetchPokemons(request: PokemonList.FetchPokemons.Request)
}

protocol PokemonListDataStore
{
    var pokemons: [Pokemon]? { get }
}

class PokemonListInteractor: PokemonListBusinessLogic, PokemonListDataStore
{
   
    var presenter: PokemonListPresentationLogic?
    var worker: PokemonListWorker? = PokemonListWorker()
    var pokemons: [Pokemon]?
    
    // MARK: Do something
    
    func fetchPokemons(request: PokemonList.FetchPokemons.Request)
    {
        worker?.fetchPokemons{ (pokemons) -> Void in
            if let pokemons = pokemons {
                self.pokemons = pokemons
                let response = PokemonList.FetchPokemons.Response(pokemons: pokemons)
                self.presenter?.presentFetchedPokemons(response: response)
            }
        }
        
    }
}
