//
//  PokemonListPresenter.swift
//  PokemonVIP
//
//  Created by Ihwan on 05/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonListPresentationLogic
{
    func presentFetchedPokemons(response: PokemonList.FetchPokemons.Response)
}

class PokemonListPresenter: PokemonListPresentationLogic
{
    weak var viewController: PokemonListDisplayLogic?
    
    func presentFetchedPokemons(response: PokemonList.FetchPokemons.Response)
    {
        var displayedPokemons: [PokemonList.FetchPokemons.ViewModel.DisplayedPokemon] = []
        for pokemon in response.pokemons {
            let displayedPokemon = PokemonList.FetchPokemons.ViewModel.DisplayedPokemon(name: pokemon.name)
            displayedPokemons.append(displayedPokemon)
        }
        let viewModel = PokemonList.FetchPokemons.ViewModel(displayedPokemons: displayedPokemons)
        viewController?.displayFetchedPokemons(viewModel: viewModel)
    }
}
