//
//  PokemonListWorker.swift
//  PokemonVIP
//
//  Created by Ihwan on 05/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PokemonListWorker
{
    func fetchPokemons(completionHandler: @escaping ([Pokemon]?) -> Void) {
        let url = URL(string: "https://api.pokemontcg.io/v2/cards")!
        let task = URLSession.shared.dataTask(with: url) { data, response, error in
            if let data = data {
                if let response = try? JSONDecoder().decode(BaseResponse.self, from: data) {
                    DispatchQueue.main.async {
                        completionHandler(response.data)
                    }
                } else {
                    print("Invalid Response")
                }
            } else if let error = error {
                print("HTTP Request Failed \(error)")
            }
        }
        task.resume()
    }
}
