name: PokemonVIP

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.1.app
    - name: Build and Test
      run: xcodebuild test -project PokemonVIP.xcodeproj -scheme "PokemonVIP" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"

