//
//  PokemonDetailModels.swift
//  PokemonVIP
//
//  Created by Ihwan on 07/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PokemonDetail
{
    // MARK: Use cases
    
    enum PokemonDetail
    {
        struct Request
        {
        }
        struct Response
        {
            var pokemon: Pokemon
        }
        struct ViewModel
        {
            struct DisplayedPokemon
            {
                var name: String
                var images: String
            }
            var displayedPokemons: DisplayedPokemon
        }
    }
}
