//
//  PokemonDetailInteractor.swift
//  PokemonVIP
//
//  Created by Ihwan on 07/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonDetailBusinessLogic
{
    func getPokemon(request: PokemonDetail.PokemonDetail.Request)
}

protocol PokemonDetailDataStore
{
    var pokemon: Pokemon? { get set }
}

class PokemonDetailInteractor: PokemonDetailBusinessLogic, PokemonDetailDataStore
{
    
    
    var presenter: PokemonDetailPresentationLogic?
    var worker: PokemonDetailWorker?
    var pokemon: Pokemon?
    
    // MARK: Do something
    
    func getPokemon(request: PokemonDetail.PokemonDetail.Request)
    {
        worker = PokemonDetailWorker()
        worker?.doSomeWork()
        
        let response = PokemonDetail.PokemonDetail.Response(pokemon: pokemon!)
        presenter?.presentDetailPokemon(response: response)
    }
}
