//
//  PokemonDetailPresenter.swift
//  PokemonVIP
//
//  Created by Ihwan on 07/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonDetailPresentationLogic
{
  func presentDetailPokemon(response: PokemonDetail.PokemonDetail.Response)
}

class PokemonDetailPresenter: PokemonDetailPresentationLogic
{
  weak var viewController: PokemonDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentDetailPokemon(response: PokemonDetail.PokemonDetail.Response)
  {
      let viewModel = PokemonDetail.PokemonDetail.ViewModel(displayedPokemons: PokemonDetail.PokemonDetail.ViewModel.DisplayedPokemon(name: response.pokemon.name, images: response.pokemon.images.small))
    viewController?.displaySomething(viewModel: viewModel)
  }
}
